### ISSUE TITLE
ethClient connect established, but contract invoke failed

### ISSUE THREAD

**Issue by huahuayu** [huahuayu/ethclient#1]
ethClient connect is successful, get contract instace also no error. But execute contract function failed.

go run main.go  result：

```
latest blockNum:  11248808
tx cost:  1140000087540000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa50abe]

goroutine 1 [running]:
github.com/ethereum/go-ethereum/ethclient.(*Client).CallContract(0x0, 0xcdd800, 0xc00002a0e8, 0x0, 0x0, 0x0, 0xc000272500, 0x0, 0x0, 0x0, ...)
        /home/shiming/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.24/ethclient/ethclient.go:478 +0x27e
github.com/ethereum/go-ethereum/accounts/abi/bind.(*BoundContract).Call(0xc000272500, 0xc0005f3f38, 0xc0005f3df8, 0xbd77cb, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/shiming/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.24/accounts/abi/bind/base.go:154 +0x662
github.com/huahuayu/ethclient/contract/hbtoken.(*HbtokenCaller).Name(0xc000644b00, 0xc0005f3f38, 0x764cd7dc61a18aa6, 0xce2dc0, 0x0, 0xc000644b00)
        /media/psf/Home/go/src/ethclient/contract/hbtoken/hbtoken.go:289 +0x85
github.com/huahuayu/ethclient/client.ContractInvoke()
        /media/psf/Home/go/src/ethclient/client/client.go:44 +0x125
main.main()
        /media/psf/Home/go/src/ethclient/main.go:7 +0x2a
exit status 2
```

**Comment by huahuayu** [comment]
The problem is solved, this line of code

```go
EthClient, err := ethclient.DialContext(ctx, "https://mainnet.infura.io/v3/e9d43fcc8b60466c9b8c6c5b8215475c")
```

Should change to this:

```go
var err error
EthClient, err = ethclient.DialContext(ctx, "https://mainnet.infura.io/v3/e9d43fcc8b60466c9b8c6c5b8215475c")
```

Otherwise, EthClient scope is changed to inside Init() function.
